### ISSUE TITLE
doesnt work on v48 anymore

### ISSUE THREAD

**Issue by ghost** [Alejo47/LC_InfiniteMoney#1]
when you buy an item it doesnt show up anymore even tho it got bought and then when you go back to the store the item is buyable again so it never buys

**Comment by Alejo47** [comment]
Hey there,
Firstly, I am assuming you mean v47 that came out today, correct? or is there a Beta version that came out today?
Secondly, I am unable to reproduce this bug, could you share the following?
* What mods do you have installed? (Profile code works too!)
* What item/items did you buy / try to buy?
* Were you playing solo or with a group?
  * If playing with a group, were you the host?

**Comment by ghost** [comment]
buying a teleporter in a lobby where the host doesnt have the mod it used to work when just one person has the mod now the money count stays 0 and the purchase sucess sound happens but doesnt go through and it doesnt buy it its version v48
![image](https://github.com/Alejo47/LC_InfiniteMoney/assets/61125650/c6d8379c-7e84-4890-9ca7-27575366aaa1)

**Comment by Alejo47** [comment]
Alright, interesting, I will look into this, I don't know if this is the response you were expecting, but unfortunately I may need to make this required by all lobby members.

**Comment by Alejo47** [comment]
Archiving repo as the mod is not as used as much anymore and still works well-enough
